services:
    Becklyn\DddGeneratorBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection, Resources}'
        autowire: true

    Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher:
        class: 'Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'
        autowire: true

    Becklyn\DddGeneratorBundle\Maker\DddMaker:
        class: 'Becklyn\DddGeneratorBundle\Maker\DddMaker'
        abstract: true
        autowire: true

    Becklyn\DddGeneratorBundle\Maker\DddEntityMaker:
        class: 'Becklyn\DddGeneratorBundle\Maker\DddEntityMaker'
        abstract: true
        autowire: true

    Becklyn\DddGeneratorBundle\Maker\MakeDomain:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\MultiClass\MakeAggregateRoot:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\MultiClass\MakeAggregateHandler:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeEntity:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeAggregateDoctrineRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeAggregateDoctrineRepositoryTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeAggregateEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeEntityCreatedEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeEntityId:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeAggregateNotFoundException:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeAggregateRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeEntityTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Entity\MakeEntityTestTrait:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'
    Becklyn\DddGeneratorBundle\Maker\Command\MakeCommand:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    Becklyn\DddGeneratorBundle\Maker\Command\MakeCommandHandler:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@Becklyn\DddGeneratorBundle\Helper\GitUserInfoFetcher'
