services:
    C201\DddGeneratorBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection, Resources}'
        autowire: true

    C201\DddGeneratorBundle\Helper\GitUserInfoFetcher:
        class: 'C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'
        autowire: true

    C201\DddGeneratorBundle\Maker\DddMaker:
        class: 'C201\DddGeneratorBundle\Maker\DddMaker'
        abstract: true
        autowire: true

    C201\DddGeneratorBundle\Maker\DddEntityMaker:
        class: 'C201\DddGeneratorBundle\Maker\DddEntityMaker'
        abstract: true
        autowire: true

    C201\DddGeneratorBundle\Maker\MakeDomain:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\MultiClass\MakeAggregateRoot:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntity:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeAggregateDoctrineRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeAggregateDoctrineRepositoryTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeAggregateEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityCreatedEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityId:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeAggregateNotFoundException:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeAggregateRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityTestTrait:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

