services:
    C201\DddGeneratorBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection, Resources}'
        autowire: true

    C201\DDDGeneratorBundle\Helper\GitUserFetcher:
        class: 'C201\DDDGeneratorBundle\Helper\GitUserFetcher'
        autowire: true

    C201\DddGeneratorBundle\Maker\DddMaker:
        class: 'C201\DddGeneratorBundle\Maker\DddMaker'
        abstract: true
        autowire: true

    C201\DddGeneratorBundle\Maker\DddEntityMaker:
        class: 'C201\DddGeneratorBundle\Maker\DddEntityMaker'
        abstract: true
        autowire: true

    C201\DddGeneratorBundle\Maker\MakeDomain:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\MultiClass\MakeAggregateRoot:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntity:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityDoctrineRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityDoctrineRepositoryTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityGeneratedEvent:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityId:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityNotFoundException:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityRepository:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityTest:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'

    C201\DddGeneratorBundle\Maker\Entity\MakeEntityTestTrait:
        tags:
            - maker.command
        arguments:
            - '@kernel'
            - '@C201\DddGeneratorBundle\Helper\GitUserInfoFetcher'
